"""
Military Data Service - Curated static data for known military installations,
nuclear facilities, and strategic waterways in the Middle East region.

All coordinates and facility information are sourced from publicly available
open-source intelligence (OSINT) data.
"""

import logging
from models import MilitaryBase, NuclearSite, Waterway

logger = logging.getLogger(__name__)


# ============================================================================
# MILITARY BASES - Real known installations in the Middle East region
# ============================================================================

_MILITARY_BASES: list[dict] = [
    # === UNITED STATES BASES IN MIDDLE EAST ===
    {
        "id": "base-al-udeid",
        "name": "Al Udeid Air Base",
        "lat": 25.1173,
        "lon": 51.3150,
        "country": "Qatar",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "United States",
        "description": "Largest US air base in Middle East. Hosts USCENTCOM forward HQ and Combined Air Operations Center (CAOC). Houses ~10,000 US personnel. Primary staging base for operations across the region.",
    },
    {
        "id": "base-al-dhafra",
        "name": "Al Dhafra Air Base",
        "lat": 24.2481,
        "lon": 54.5478,
        "country": "United Arab Emirates",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "United States / UAE",
        "description": "Joint UAE-US base. Hosts US F-35s, F-22s, KC-10 tankers, RQ-4 Global Hawks. Key ISR and refueling hub for the Persian Gulf region.",
    },
    {
        "id": "base-camp-arifjan",
        "name": "Camp Arifjan",
        "lat": 28.9539,
        "lon": 48.0992,
        "country": "Kuwait",
        "type": "army_base",
        "branch": "army",
        "status": "active",
        "operator": "United States",
        "description": "US Army Central (ARCENT) forward HQ. Largest US Army installation in Southwest Asia. Major logistics and command hub with ~13,000 personnel.",
    },
    {
        "id": "base-incirlik",
        "name": "Incirlik Air Base",
        "lat": 37.0021,
        "lon": 35.4259,
        "country": "Turkey",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "United States / Turkey",
        "description": "Joint Turkish-US air base near Adana. Reportedly houses US tactical nuclear weapons (B61 bombs). Critical for operations against ISIS and regional deterrence.",
    },
    {
        "id": "base-nsa-bahrain",
        "name": "Naval Support Activity Bahrain",
        "lat": 26.2361,
        "lon": 50.6081,
        "country": "Bahrain",
        "type": "naval_base",
        "branch": "navy",
        "status": "active",
        "operator": "United States",
        "description": "Home port of US Fifth Fleet and Naval Forces Central Command (NAVCENT). Hosts Combined Maritime Forces and multiple carrier strike group rotations.",
    },
    {
        "id": "base-prince-sultan",
        "name": "Prince Sultan Air Base",
        "lat": 24.0627,
        "lon": 47.5804,
        "country": "Saudi Arabia",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "United States / Saudi Arabia",
        "description": "Al Kharj airfield. Reactivated for US forces in 2019. Hosts US Patriot batteries, fighter squadrons, and THAAD missile defense systems.",
    },
    {
        "id": "base-al-salem",
        "name": "Ali Al Salem Air Base",
        "lat": 29.3467,
        "lon": 47.5208,
        "country": "Kuwait",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "United States / Kuwait",
        "description": "Major transit hub for US forces in the region. Processes personnel movements in and out of theater. Fighter and support aircraft operations.",
    },
    {
        "id": "base-camp-buehring",
        "name": "Camp Buehring",
        "lat": 29.7897,
        "lon": 47.0772,
        "country": "Kuwait",
        "type": "army_base",
        "branch": "army",
        "status": "active",
        "operator": "United States",
        "description": "US Army base in northwestern Kuwait. Used for troop staging, training, and acclimatization before deployment into theater.",
    },
    {
        "id": "base-al-minhad",
        "name": "Al Minhad Air Base",
        "lat": 25.0272,
        "lon": 55.3661,
        "country": "United Arab Emirates",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "UAE / Coalition",
        "description": "UAE Air Force base near Dubai. Hosts Australian, Canadian, and coalition aircraft for Middle East operations.",
    },
    # === SAUDI ARABIAN MILITARY ===
    {
        "id": "base-king-abdulaziz",
        "name": "King Abdulaziz Air Base",
        "lat": 26.2653,
        "lon": 50.1523,
        "country": "Saudi Arabia",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Saudi Arabia",
        "description": "Major Royal Saudi Air Force base near Dhahran. Hosts F-15 squadrons and AWACS aircraft. Key Persian Gulf coastal defense.",
    },
    {
        "id": "base-king-faisal",
        "name": "King Faisal Air Base",
        "lat": 27.9008,
        "lon": 45.5281,
        "country": "Saudi Arabia",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Saudi Arabia",
        "description": "Royal Saudi Air Force base at Tabuk in northwestern Saudi Arabia. F-15 and Tornado squadrons for northern border defense.",
    },
    {
        "id": "base-king-khalid",
        "name": "King Khalid Air Base",
        "lat": 18.2973,
        "lon": 42.8036,
        "country": "Saudi Arabia",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Saudi Arabia",
        "description": "RSAF base at Khamis Mushait near Yemen border. Primary staging base for Saudi operations in Yemen. Hosts Typhoon and F-15 fighters.",
    },
    {
        "id": "base-king-fahd-naval",
        "name": "King Abdulaziz Naval Base",
        "lat": 21.4225,
        "lon": 39.1700,
        "country": "Saudi Arabia",
        "type": "naval_base",
        "branch": "navy",
        "status": "active",
        "operator": "Saudi Arabia",
        "description": "Major Royal Saudi Naval Forces western fleet base in Jeddah. Red Sea operations and maritime security.",
    },
    # === ISRAELI MILITARY ===
    {
        "id": "base-nevatim",
        "name": "Nevatim Air Base",
        "lat": 31.2083,
        "lon": 34.9228,
        "country": "Israel",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Israel",
        "description": "Israel Air Force base in the Negev. Hosts Israel's F-35I Adir stealth fighters. One of Israel's most important strategic air bases.",
    },
    {
        "id": "base-ramon",
        "name": "Ramon Air Base",
        "lat": 30.7761,
        "lon": 34.6667,
        "country": "Israel",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Israel",
        "description": "IAF base in southern Negev near Eilat. Hosts F-16I Sufa squadrons. Israel's southernmost air base, strategic for Red Sea and Iranian threat axis.",
    },
    {
        "id": "base-ramat-david",
        "name": "Ramat David Air Base",
        "lat": 32.6650,
        "lon": 35.1794,
        "country": "Israel",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Israel",
        "description": "IAF base in northern Israel. Hosts F-16 and helicopter squadrons. Key for northern front operations against Hezbollah and Syria.",
    },
    {
        "id": "base-palmachim",
        "name": "Palmachim Air Base",
        "lat": 31.8975,
        "lon": 34.6906,
        "country": "Israel",
        "type": "combined",
        "branch": "combined",
        "status": "active",
        "operator": "Israel",
        "description": "IAF base south of Tel Aviv. Israel's missile test range. Launch site for Shavit space launch vehicle and Arrow missile defense system tests.",
    },
    {
        "id": "base-haifa-naval",
        "name": "Haifa Naval Base",
        "lat": 32.8231,
        "lon": 35.0003,
        "country": "Israel",
        "type": "naval_base",
        "branch": "navy",
        "status": "active",
        "operator": "Israel",
        "description": "Israel Navy main base. Home port for Sa'ar corvettes and Dolphin-class submarines (reportedly nuclear-capable). Mediterranean fleet operations.",
    },
    # === RUSSIAN BASES IN SYRIA ===
    {
        "id": "base-hmeimim",
        "name": "Khmeimim (Hmeimim) Air Base",
        "lat": 35.4008,
        "lon": 35.9486,
        "country": "Syria",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Russia",
        "description": "Russia's primary air base in Syria near Latakia. Hosts Su-35, Su-34, Su-24 fighters, S-400 air defense. Russia's power projection hub in the Eastern Mediterranean.",
    },
    {
        "id": "base-tartus",
        "name": "Tartus Naval Facility",
        "lat": 34.8890,
        "lon": 35.8866,
        "country": "Syria",
        "type": "naval_base",
        "branch": "navy",
        "status": "active",
        "operator": "Russia",
        "description": "Russia's only Mediterranean naval resupply point. Expanded significantly since 2015. Supports Russian naval operations and submarine movements.",
    },
    # === TURKISH MILITARY ===
    {
        "id": "base-diyarbakir",
        "name": "Diyarbakir Air Base",
        "lat": 37.8939,
        "lon": 40.2017,
        "country": "Turkey",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Turkey",
        "description": "Turkish Air Force 8th Main Jet Base. Hosts F-16 squadrons. Key for operations in southeastern Turkey, northern Iraq, and northern Syria.",
    },
    {
        "id": "base-batman",
        "name": "Batman Air Base",
        "lat": 37.9290,
        "lon": 41.1186,
        "country": "Turkey",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Turkey",
        "description": "Turkish Air Force base for southeastern operations. Used for cross-border operations into northern Iraq against PKK targets.",
    },
    {
        "id": "base-aksaz",
        "name": "Aksaz Naval Base",
        "lat": 36.9608,
        "lon": 28.3858,
        "country": "Turkey",
        "type": "naval_base",
        "branch": "navy",
        "status": "active",
        "operator": "Turkey",
        "description": "Turkish Navy Southern Area Command. Major naval facility on the Aegean coast. Hosts frigates and submarines for Eastern Mediterranean operations.",
    },
    # === IRANIAN MILITARY ===
    {
        "id": "base-isfahan-afb",
        "name": "Isfahan Air Base (Shahid Babaei)",
        "lat": 32.7500,
        "lon": 51.8617,
        "country": "Iran",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Iran",
        "description": "IRIAF major tactical fighter base. Hosts F-14 Tomcats (Iran's primary air superiority fighters), F-4 Phantoms. Central Iran strategic air defense.",
    },
    {
        "id": "base-tabriz",
        "name": "Tabriz Air Base (Shahid Fakouri)",
        "lat": 38.1339,
        "lon": 46.2350,
        "country": "Iran",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Iran",
        "description": "IRIAF base in northwestern Iran. Hosts F-5, Su-24 aircraft. Key for Caucasus and Turkish border air defense. Near Azerbaijan border.",
    },
    {
        "id": "base-bushehr-afb",
        "name": "Bushehr Air Base",
        "lat": 28.9628,
        "lon": 50.8356,
        "country": "Iran",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Iran",
        "description": "IRIAF base on Persian Gulf coast near Bushehr nuclear plant. Anti-ship missile batteries. Coastal defense for Iran's nuclear facilities.",
    },
    {
        "id": "base-bandar-abbas",
        "name": "Bandar Abbas Naval Base",
        "lat": 27.1483,
        "lon": 56.2822,
        "country": "Iran",
        "type": "naval_base",
        "branch": "navy",
        "status": "active",
        "operator": "Iran",
        "description": "IRIN (Islamic Republic of Iran Navy) main base on the Strait of Hormuz. Commands Iran's naval control over the strait. Hosts frigates, submarines, and fast attack craft.",
    },
    {
        "id": "base-chabahar",
        "name": "Chabahar Naval Base",
        "lat": 25.3000,
        "lon": 60.6167,
        "country": "Iran",
        "type": "naval_base",
        "branch": "navy",
        "status": "active",
        "operator": "Iran",
        "description": "IRIN naval base on the Gulf of Oman outside the Strait of Hormuz. Strategic for Indian Ocean operations. Also hosts IRGC Navy fast boats.",
    },
    {
        "id": "base-parchin",
        "name": "Parchin Military Complex",
        "lat": 35.5236,
        "lon": 51.7714,
        "country": "Iran",
        "type": "combined",
        "branch": "combined",
        "status": "active",
        "operator": "Iran",
        "description": "Major military research and weapons development complex southeast of Tehran. Suspected of past nuclear weapons-related high explosive testing. IAEA has sought access.",
    },
    {
        "id": "base-imam-ali",
        "name": "Imam Ali Missile Base",
        "lat": 33.4300,
        "lon": 48.7200,
        "country": "Iran",
        "type": "missile_base",
        "branch": "combined",
        "status": "active",
        "operator": "Iran (IRGC)",
        "description": "IRGC Aerospace Force ballistic missile base in Lorestan province. Reported Shahab-3 and Emad medium-range ballistic missile storage and launch site.",
    },
    # === EGYPTIAN MILITARY ===
    {
        "id": "base-cairo-west",
        "name": "Cairo West Air Base",
        "lat": 30.1164,
        "lon": 30.9153,
        "country": "Egypt",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Egypt",
        "description": "Egyptian Air Force major base west of Cairo. Hosts F-16, Rafale, and MiG-29 squadrons. Egypt's primary air defense fighter base.",
    },
    {
        "id": "base-berenice",
        "name": "Berenice Military Base",
        "lat": 23.9300,
        "lon": 35.4900,
        "country": "Egypt",
        "type": "combined",
        "branch": "combined",
        "status": "active",
        "operator": "Egypt",
        "description": "New large Egyptian military base on the Red Sea coast. Naval and air facilities. Strategic for Red Sea security and Bab el-Mandeb strait approaches.",
    },
    # === JORDANIAN MILITARY ===
    {
        "id": "base-muwaffaq-salti",
        "name": "Muwaffaq Salti Air Base",
        "lat": 32.3564,
        "lon": 36.2592,
        "country": "Jordan",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "Jordan / United States",
        "description": "Royal Jordanian Air Force base near Azraq. US drone operations and F-16 deployments. Key staging point for coalition operations in Syria and Iraq.",
    },
    # === UAE MILITARY ===
    {
        "id": "base-sweihan",
        "name": "Sweihan Air Base",
        "lat": 24.4500,
        "lon": 55.5000,
        "country": "United Arab Emirates",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "United Arab Emirates",
        "description": "UAE Air Force and Air Defence base. Hosts Mirage 2000 and F-16E/F Block 60 Desert Falcon fighters. Primary UAE combat air power base.",
    },
    # === BRITISH BASE ===
    {
        "id": "base-akrotiri",
        "name": "RAF Akrotiri",
        "lat": 34.5908,
        "lon": 32.9878,
        "country": "Cyprus (UK Sovereign Base)",
        "type": "air_base",
        "branch": "air_force",
        "status": "active",
        "operator": "United Kingdom",
        "description": "British Sovereign Base Area in Cyprus. RAF Typhoon and surveillance aircraft. Staging base for UK operations in the Middle East and Eastern Mediterranean.",
    },
    # === FRENCH BASE ===
    {
        "id": "base-abu-dhabi-french",
        "name": "French Naval Base Abu Dhabi",
        "lat": 24.5300,
        "lon": 54.6500,
        "country": "United Arab Emirates",
        "type": "combined",
        "branch": "combined",
        "status": "active",
        "operator": "France",
        "description": "France's permanent military base in the UAE (Camp de la Paix). Hosts ~700 personnel, Rafale fighters, naval vessels. France's largest base in the Gulf.",
    },
    # === DJIBOUTIAN BASES (Strategic for ME) ===
    {
        "id": "base-camp-lemonnier",
        "name": "Camp Lemonnier",
        "lat": 11.5469,
        "lon": 43.1586,
        "country": "Djibouti",
        "type": "combined",
        "branch": "combined",
        "status": "active",
        "operator": "United States",
        "description": "US military base in Djibouti. Hosts CJTF-Horn of Africa, drone operations, special forces. Controls approaches to Bab el-Mandeb strait and Red Sea.",
    },
]


# ============================================================================
# NUCLEAR SITES - Known nuclear facilities in the region
# ============================================================================

_NUCLEAR_SITES: list[dict] = [
    # === IRAN ===
    {
        "id": "nuke-bushehr",
        "name": "Bushehr Nuclear Power Plant",
        "lat": 28.8317,
        "lon": 50.8881,
        "country": "Iran",
        "type": "power_plant",
        "status": "active",
        "description": "Iran's only operational nuclear power plant. Russian-built VVER-1000 reactor (1,000 MWe). Began commercial operation in 2013. Under IAEA safeguards. Located on the Persian Gulf coast.",
    },
    {
        "id": "nuke-natanz",
        "name": "Natanz Uranium Enrichment Facility",
        "lat": 33.7250,
        "lon": 51.7264,
        "country": "Iran",
        "type": "enrichment",
        "status": "active",
        "description": "Iran's primary uranium enrichment facility. Large underground halls with thousands of IR centrifuges. Target of Stuxnet cyberattack (2010). Enriching to 60% U-235 as of 2023. Heavily fortified underground.",
    },
    {
        "id": "nuke-fordow",
        "name": "Fordow Fuel Enrichment Plant",
        "lat": 34.8803,
        "lon": 51.5653,
        "country": "Iran",
        "type": "enrichment",
        "status": "active",
        "description": "Deeply buried enrichment facility near Qom, built inside a mountain. Houses advanced IR-6 centrifuges. Enriching uranium to 60%. Considered very difficult to destroy militarily due to depth of burial.",
    },
    {
        "id": "nuke-isfahan-ucf",
        "name": "Isfahan Uranium Conversion Facility",
        "lat": 32.6500,
        "lon": 51.6833,
        "country": "Iran",
        "type": "research",
        "status": "active",
        "description": "Isfahan Nuclear Technology Center. Converts yellowcake to UF6 (uranium hexafluoride) for enrichment. Also houses multiple research reactors and fuel fabrication facilities.",
    },
    {
        "id": "nuke-arak",
        "name": "Arak Heavy Water Reactor (IR-40)",
        "lat": 34.0439,
        "lon": 49.2436,
        "country": "Iran",
        "type": "reactor",
        "status": "active",
        "description": "Arak IR-40 heavy water research reactor. Redesigned under JCPOA to reduce plutonium production. Co-located with heavy water production plant. Potential plutonium pathway concern.",
    },
    {
        "id": "nuke-parchin-research",
        "name": "Parchin Nuclear Research Site",
        "lat": 35.5236,
        "lon": 51.7714,
        "country": "Iran",
        "type": "research",
        "status": "active",
        "description": "Military complex southeast of Tehran. IAEA detected uranium particles at specific buildings. Suspected past weaponization research including explosive bridge-wire detonator testing.",
    },
    {
        "id": "nuke-tehran-research",
        "name": "Tehran Research Reactor (TRR)",
        "lat": 35.7383,
        "lon": 51.3883,
        "country": "Iran",
        "type": "research",
        "status": "active",
        "description": "5 MW pool-type research reactor at University of Tehran. US-supplied (1967), converted from HEU to LEU fuel. Produces medical isotopes. Under IAEA safeguards.",
    },
    # === ISRAEL ===
    {
        "id": "nuke-dimona",
        "name": "Negev Nuclear Research Center (Dimona)",
        "lat": 31.0014,
        "lon": 35.1447,
        "country": "Israel",
        "type": "weapons",
        "status": "active",
        "description": "Israel's nuclear weapons production facility in the Negev desert. Houses the IRR-2 heavy water reactor and plutonium reprocessing plant. Israel maintains nuclear ambiguity policy. Estimated 80-400 warheads.",
    },
    {
        "id": "nuke-soreq",
        "name": "Soreq Nuclear Research Center",
        "lat": 31.7667,
        "lon": 34.7000,
        "country": "Israel",
        "type": "research",
        "status": "active",
        "description": "Nuclear research center near Yavne. Houses the IRR-1 light water research reactor (US-supplied). Conducts nuclear physics research, medical isotope production, and accelerator research.",
    },
    # === UAE ===
    {
        "id": "nuke-barakah",
        "name": "Barakah Nuclear Power Plant",
        "lat": 23.9575,
        "lon": 52.2564,
        "country": "United Arab Emirates",
        "type": "power_plant",
        "status": "active",
        "description": "UAE's first nuclear power plant. Four South Korean APR-1400 reactors (5,600 MWe total). Units 1-3 operational, Unit 4 under commissioning. Located in Al Dhafra region. Under IAEA safeguards.",
    },
    # === PAKISTAN (regional nuclear power) ===
    {
        "id": "nuke-chashma",
        "name": "Chashma Nuclear Power Complex",
        "lat": 32.3833,
        "lon": 71.4667,
        "country": "Pakistan",
        "type": "power_plant",
        "status": "active",
        "description": "Four Chinese-supplied CNP-300/600 pressurized water reactors in Punjab. Pakistan's primary nuclear power generation site. Under IAEA safeguards.",
    },
    {
        "id": "nuke-kahuta",
        "name": "Khan Research Laboratories (Kahuta)",
        "lat": 33.5833,
        "lon": 73.4000,
        "country": "Pakistan",
        "type": "enrichment",
        "status": "active",
        "description": "Pakistan's primary uranium enrichment facility. Key facility in Pakistan's nuclear weapons program. Named after A.Q. Khan. Gas centrifuge enrichment for weapons-grade uranium.",
    },
    # === EGYPT (research only) ===
    {
        "id": "nuke-inshas",
        "name": "Inshas Nuclear Research Center",
        "lat": 30.2967,
        "lon": 31.4050,
        "country": "Egypt",
        "type": "research",
        "status": "active",
        "description": "Egypt's main nuclear research center near Cairo. Houses ETRR-2 research reactor (22 MW, Argentine-supplied). Nuclear physics research and medical isotope production.",
    },
    {
        "id": "nuke-dabaa",
        "name": "El Dabaa Nuclear Power Plant",
        "lat": 31.0333,
        "lon": 28.4500,
        "country": "Egypt",
        "type": "power_plant",
        "status": "under_construction",
        "description": "Egypt's first nuclear power plant under construction on the Mediterranean coast. Four Russian VVER-1200 reactors (4,800 MWe total). Expected completion mid-2030s. Russian-financed and built.",
    },
    # === TURKEY (planned) ===
    {
        "id": "nuke-akkuyu",
        "name": "Akkuyu Nuclear Power Plant",
        "lat": 36.1444,
        "lon": 33.5347,
        "country": "Turkey",
        "type": "power_plant",
        "status": "under_construction",
        "description": "Turkey's first nuclear power plant on the Mediterranean coast. Four Russian VVER-1200 reactors (4,800 MWe). Built by Rosatom under BOO model. Unit 1 expected operational by 2025.",
    },
    # === JORDAN (research) ===
    {
        "id": "nuke-jordan-research",
        "name": "Jordan Research and Training Reactor (JRTR)",
        "lat": 32.3500,
        "lon": 36.0500,
        "country": "Jordan",
        "type": "research",
        "status": "active",
        "description": "5 MW research reactor at Jordan University of Science and Technology. South Korean-supplied. Used for neutron research, radioisotope production, and education.",
    },
]


# ============================================================================
# STRATEGIC WATERWAYS - Critical maritime chokepoints
# ============================================================================

_WATERWAYS: list[dict] = [
    {
        "id": "waterway-hormuz",
        "name": "Strait of Hormuz",
        "lat": 26.5667,
        "lon": 56.2500,
        "type": "strait",
        "description": "World's most critical oil chokepoint between Iran and Oman/UAE. Approximately 21 nautical miles wide at narrowest point. ~21 million barrels of oil transit daily (~21% of global consumption). Iran has repeatedly threatened to close it.",
        "daily_traffic": "~21 million barrels oil/day, hundreds of vessels",
        "strategic_importance": "critical",
        "controlled_by": "Iran / Oman (shared)",
        "coordinates": [
            [26.75, 56.10], [26.60, 56.25], [26.40, 56.40],
            [26.20, 56.50], [26.00, 56.60],
        ],
    },
    {
        "id": "waterway-suez",
        "name": "Suez Canal",
        "lat": 30.4583,
        "lon": 32.3500,
        "type": "canal",
        "description": "193 km artificial waterway connecting Mediterranean to Red Sea via Egypt. ~12-15% of global trade transits through. ~50 ships per day. Expanded in 2015 with New Suez Canal parallel channel. Ever Given blockage (2021) demonstrated global supply chain vulnerability.",
        "daily_traffic": "~50 vessels/day, ~12% of global trade",
        "strategic_importance": "critical",
        "controlled_by": "Egypt (Suez Canal Authority)",
        "coordinates": [
            [31.27, 32.31], [30.85, 32.32], [30.58, 32.34],
            [30.42, 32.35], [30.02, 32.58], [29.93, 32.57],
        ],
    },
    {
        "id": "waterway-bab-el-mandeb",
        "name": "Bab el-Mandeb Strait",
        "lat": 12.5833,
        "lon": 43.3333,
        "type": "strait",
        "description": "Strait between Yemen and Djibouti/Eritrea connecting Red Sea to Gulf of Aden. ~20 miles wide. ~6.2 million barrels of oil/day. Houthi attacks on commercial shipping since 2023 have severely disrupted traffic. US/UK military operations to protect shipping.",
        "daily_traffic": "~6.2 million barrels oil/day",
        "strategic_importance": "critical",
        "controlled_by": "Yemen / Djibouti (contested - Houthi threat)",
        "coordinates": [
            [12.80, 43.20], [12.60, 43.30], [12.40, 43.40],
            [12.20, 43.50],
        ],
    },
    {
        "id": "waterway-turkish-straits",
        "name": "Turkish Straits (Bosphorus & Dardanelles)",
        "lat": 41.1167,
        "lon": 29.0750,
        "type": "strait",
        "description": "Two narrow waterways connecting Black Sea to Mediterranean via Sea of Marmara. Bosphorus is only 700m wide at narrowest. ~3 million barrels of oil/day. Critical for Russian energy exports. Governed by Montreux Convention (1936) giving Turkey control.",
        "daily_traffic": "~48,000 vessels/year, ~3 million barrels oil/day",
        "strategic_importance": "critical",
        "controlled_by": "Turkey (Montreux Convention)",
        "coordinates": [
            [41.22, 29.05], [41.12, 29.07], [41.02, 29.03],
            [40.68, 29.55], [40.40, 26.67], [40.20, 26.40],
        ],
    },
    {
        "id": "waterway-persian-gulf",
        "name": "Persian Gulf Shipping Lanes",
        "lat": 27.0000,
        "lon": 51.0000,
        "type": "passage",
        "description": "Major shipping routes through the Persian Gulf carrying significant portion of global oil supply. Multiple VLCC tanker routes between Gulf ports and Strait of Hormuz. Monitored by US Fifth Fleet from Bahrain.",
        "daily_traffic": "Multiple VLCC tankers, naval patrols",
        "strategic_importance": "critical",
        "controlled_by": "Multiple nations / US Fifth Fleet patrols",
        "coordinates": [
            [29.30, 48.80], [28.00, 50.50], [27.00, 51.50],
            [26.50, 53.00], [26.00, 55.00], [26.50, 56.20],
        ],
    },
]


def get_military_bases() -> list[MilitaryBase]:
    """Return all known military installations in the Middle East region."""
    bases = [MilitaryBase(**data) for data in _MILITARY_BASES]
    logger.info("Loaded %d military bases", len(bases))
    return bases


def get_nuclear_sites() -> list[NuclearSite]:
    """Return all known nuclear facilities in the Middle East region."""
    sites = [NuclearSite(**data) for data in _NUCLEAR_SITES]
    logger.info("Loaded %d nuclear sites", len(sites))
    return sites


def get_waterways() -> list[Waterway]:
    """Return strategic waterway and chokepoint data."""
    waterways = [Waterway(**data) for data in _WATERWAYS]
    logger.info("Loaded %d strategic waterways", len(waterways))
    return waterways
